spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: PFT8462
    password: PFT8462
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
    #      ddl-auto: create-drop
    #      generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        proc:
          param_null_passing: true

  server:
    port: 8083