spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ControlTareas
    password: ControlTareas
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    show-sql: true
